vlm/src/main/scala/geotrellis/contrib/vlm/GeoTiffResampleRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/LayoutTileSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/ResampleGrid.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALBaseRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALResampleRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALWarpOptions.scala, vlm/src/test/scala/geotrellis/contrib/vlm/GeoTiffRasterSourceSpec.scala, vlm/src/test/scala/geotrellis/contrib/vlm/gdal/GDALRasterSourceSpec.scala, vlm/src/test/scala/geotrellis/contrib/vlm/gdal/GDALReaderSpec.scala
This PR adds the `tileToLayout` method to `RasterSource` which will allow users to apply a layout on their source data.
Resolves #30
=> tileToLayout for RasterSource

build.sbt
This PR bumps the version number of geotrellis vlm from 0.1.1 to 0.2.0
=> 0.2.0 Release

build.sbt
This PR bumps the version number of geotrellis vlm from `0.2.0` to `0.3.0-SNAPSHOT`
=> 0.3.0-SNAPSHOT Release

vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALBaseRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALResampleRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/gdal/GDALWarpOptions.scala, vlm/src/test/scala/geotrellis/contrib/vlm/RasterSummarySpec.scala, vlm/src/test/scala/geotrellis/contrib/vlm/gdal/GDALRasterSourceSpec.scala
`-tap just aligns the grid to the resolution`, so probably we don't need it always, as sometimes it can round extent incorrectly.
Fixes https://github.com/geotrellis/geotrellis-contrib/issues/45
=> Add a pixelAlignment flag

project/Dependencies.scala, vlm/src/main/resources/reference.conf, vlm/src/test/scala/geotrellis/contrib/vlm/RasterSourceRDDSpec.scala, vlm/src/test/scala/geotrellis/contrib/vlm/RasterSummarySpec.scala
This new GT-GDAL version sets options to prevent SEGSEV failures.
=> Depend on a new GDAL version

vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/test/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSourceSpec.scala
Original code would use the `cellSize` in target CRS to select overview resolution in source CRS.
Previous unit tests did not catch it because they were between `lcc` and `merc` which both have units in meters, so the results where within margin of error.
Closes: https://github.com/geotrellis/geotrellis-contrib/issues/73
=> Fix source overview selection in GeoTiffReprojectRasterSource

vlm/src/main/scala/geotrellis/contrib/vlm/PaddedTile.scala, vlm/src/test/scala/geotrellis/contrib/vlm/PaddedTileSpec.scala
- `foreach` and `map` visitors were getting col/row values relative to chunk rather than padded tile itself
- Imposed row-major traversal order in `foreach(z)` and `foreachDouble(x)` methods
These were discovered via a bug that shifted the data region to upper left corner when a tile was being rendered.
=> Fix PaddedTile foreach and map visitors

project/Dependencies.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisResampleRasterSource.scala, vlm/src/test/scala/geotrellis/contrib/vlm/avro/GeotrellisRasterSourceSpec.scala
Add resampling and reprojecting to `GeotrellisRasterSource` via the new `GeotrellisResampleRasterSource` and `GeotrellisReprojectRasterSource` classes.
The common functionality between the three classes was broken out into the `GeotrellisRasterSource` object in an effort to avoid duplication and improve testability.
The test for reprojection is currently not passing. I think it's close but it might require some love from @echeipesh to push it over the finish line. See: https://github.com/geotrellis/geotrellis-contrib/blob/9fba2db98f15072707c4bdc1f7eeec99e11277c0/vlm/src/test/scala/geotrellis/contrib/vlm/avro/GeotrellisRasterSourceSpec.scala#L178
=> Add resampling and reprojecting to GeotrellisRasterSource

vlm/src/main/scala/geotrellis/contrib/vlm/RasterSourceRDD.scala, vlm/src/main/scala/geotrellis/contrib/vlm/ReadingSource.scala, vlm/src/test/scala/geotrellis/contrib/vlm/RasterSourceRDDSpec.scala
This PR adds the `read` method to `RasterSourceRDD`. This method will take in any number of `ReadingSource`s and convert them into a single `MultibandTile` based on the order of the bands given.
=> Band Multiplexing

vlm/src/main/resources/reference.conf, vlm/src/main/scala/geotrellis/contrib/vlm/Config.scala, vlm/src/main/scala/geotrellis/contrib/vlm/package.scala
Overview
-----
This PR creates a configuration key to allow global s3 bucket access. It's useful for client applications in which the location of imagery isn't controlled by the application, but by users of the application.
Testing
-----
I get instant console rot every time I try to open up a console, so I'm not sure what testing looks like
Related to #70
=> Allow s3 client configuration for global object access

vlm/src/main/scala/geotrellis/contrib/vlm/RasterSourceRDD.scala
This PR adds the `readFromRDD` method to `RasterSourceRDD` that will create a `MultibandTileLayer` from an `RDD[ReadingSource]`. In addition to this new method, a small fix has been done in the `read` method that improves the partitioning of that method.
=> readFromRDD Method and Small Fix to the read Method

vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisReprojectRasterSource.scala
This PR fixes a typo in the `GeotrellisReprojectRasterSource.reproject` method.
=> Typo Fix in GeotrellisReprojectRaterSource.reproject

build.sbt, project/Dependencies.scala, summary/src/main/scala/geotrellis/contrib/polygonal/CellAccumulator.scala, summary/src/main/scala/geotrellis/contrib/polygonal/Implicits.scala, summary/src/main/scala/geotrellis/contrib/polygonal/PolygonalSummary.scala
Enables usage like:
```scala
val Feature(geom, histogram) = raster.polygonalSummary[Polygon, StreamingHistogram](feature.geom)
```
Core interface is
```scala
/** Polygonal summary over for pixels under geomery.
* The feature data value will be used as a starting point of the accumulator.
*
* @param self Raster-like type containing pixel data
* @param feature Geometry for area of summery
* @param options Rasterizer options determine which pixels are judged to be intersecting the geometry.
*/
def polygonalSummary[G <: Geometry, R: CellAccumulator: Monoid](self: T, feature: Feature[G, R], options: Rasterizer.Options): Feature[G, R]
```
This is intended as foundation for replacement for polygonal summary code under:
https://github.com/locationtech/geotrellis/tree/master/raster/src/main/scala/g …
=> PolygonalSummary Type Class

gdal/src/it/scala/geotrellis/contrib/vlm/SubsceneReadingIT.scala, project/Dependencies.scala
This improves performance on the first test:
```
[info] GDAL vs GeoTrellis GeoTiff reading
18:27:18 SubsceneReadingIT: Elapsed time of GeoTrellis is 1.1300s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),EPSG:3857)
18:27:20 SubsceneReadingIT: Elapsed time of GDAL is 1.5630s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),merc-CS)
[info] - should read projected extent with similar performance with GDAL (2 seconds, 855 milliseconds)
18:27:22 SubsceneReadingIT: Elapsed time of GeoTrellis is 1.9370s, producing Some(372620)
18:27:23 SubsceneReadingIT: Elapsed time of GDAL is 1.3360s, producing Some(372620)
```
but now the third (but never the fourth) test …
=> Improve GDAL Performance on Integration Tests

gdal/src/test/scala/geotrellis/contrib/vlm/spark/GDALRasterSummarySpec.scala, gdal/version.sbt, project/Dependencies.scala, summary/version.sbt, testkit/version.sbt, version.sbt, vlm/version.sbt
Bumping version to `3.x` to make it easier to keep track of this series are those compatible with GeoTrellis 3.x milestones and eventually release.
=> GeoTrellis 3.0.0-M3, Version 3.11

gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALRasterSource.scala, gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALWarpOptions.scala, gdal/src/main/scala/geotrellis/contrib/vlm/gdal/Implicits.scala
GDALWarpOptions convert should be applied in the same way `options.{reproject | resample}` functions are applied.
=> Refactor GDALWarpOptions.convert

vlm/src/main/scala/geotrellis/contrib/vlm/MosaicRasterSource.scala
This PR addresses a bug in MosaicRasterSource where sometimes extents won't end up combinable after `ceil`.
Working on testing instructions, just leaving this here for a minute
=> Round instead of ceil for combining raster extents

CHANGELOG.md, vlm/src/main/scala/geotrellis/contrib/vlm/spark/RasterSourceRDD.scala
This PR fixes the number of partitions that the resulting `RDD` has when created via `RasterSourceRDD.read` or `RasterSourceRDD.tileLayerRDD`. Now, it will look at the number of partitions the given `RDD`, and will use that number if it's more than the what is produced by `estimatePartitionsNumber`
Closes #129
=> RasterSourceRDD Partition Count Fix

project/Dependencies.scala
Closes #176
@pomadchin Can you publish a new version of this to bintray?
=> Upgrade 2.x branch to newer gdal-warp

CHANGELOG.md, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffResampleRasterSource.scala, vlm/src/test/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSourceMultiThreadingSpec.scala, vlm/src/test/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSourceSpec.scala
This PR makes reading from `GeoTiffRasterSource`s thread safe by synchronizing the `tiff` objects within these instances. That will ensure that the state of the data doesn't change as it's being accessed by different threads.
Closes https://github.com/locationtech/geotrellis/issues/2954
=> GeoTiffRasterSource Thread Safety

CHANGELOG.md, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffResampleRasterSource.scala, vlm/src/test/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSourceMultiThreadingSpec.scala
This PR improves the performance of `GeoTiffRasterSource`s by having the base tiff be an optional constructor. This will prevent the same Tiff being reread multiple times during a job.
Closes #155
=> GeoTiffRasterSource Tiff Reuse

LICENSE
Was looking for the correct official name of Azavea for use in LICENSEs, went here and noticed it was missing. So now its updated.
=> Add Azavea and year to LICENSE

CHANGELOG.md, gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALRasterSource.scala, gdal/src/test/scala/geotrellis/contrib/vlm/gdal/GDALWarpOptionsSpec.scala, vlm/src/main/scala/geotrellis/contrib/vlm/MosaicRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/RasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/avro/GeotrellisResampleRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffResampleRasterSource.scala
This PR adds logic that checks to see if the target `RasterSource` need to be reprojected. If they don't, then they are either resampled are just returned as-is.
Closes #102
=> Reprojection Short Circuting

vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala
This PR marks `transform` fields as `transient` since they are not serializable, for more details see https://github.com/locationtech/proj4j/pull/34
```bash
GEOTRELLIS_USE_JAVA_SER=TRUE ./sbt 
```
Partially addresses https://github.com/geotrellis/geotrellis-contrib/issues/226
=> Make RasterSources Java serializable

vlm/src/main/scala/geotrellis/contrib/vlm/effect/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/effect/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/effect/geotiff/GeoTiffResampleRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffReprojectRasterSource.scala, vlm/src/main/scala/geotrellis/contrib/vlm/geotiff/GeoTiffResampleRasterSource.scala
Addresses https://github.com/geotrellis/geotrellis-contrib/issues/226 as well. 
In some cases GeoTiffs would not be serializable due to having non serializable byte buffers. 
Probably a better solution would be to improve GeoTiff class and make it serializable, so it is probably a temporal solution.
Closes #226
=> Make baseTiff transient
